// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

using System;
using System.Numerics;
using ProjectEulerLib;

namespace Problem2
{
    class Problem2
    {
        const int MAXSIZE = 4000000;

        static void Main(string[] args)
        {
            int i = 0;
            BigInteger result = BigInteger.Zero;

            while (MathUtils.Fibonacci(i) < MAXSIZE)
            {
                ++i;

                if (MathUtils.Fibonacci(i) % 2 == 0)
                {
                    result += MathUtils.Fibonacci(i);
                }
            }
            Console.WriteLine(result);
            Console.ReadKey();
        }
    }
}
